language: haskell
ghc:
    - 7.6

before_install:
    - cd neptune/
    - cabal install --only-dependencies --enable-tests
install:
    - cabal install --enable-tests
script:
    - 

notifications:
    email:
        on_success: never
        on_failure: change