language: haskell
ghc:
    - 7.6

before_install:
    - cabal update
    - cabal install --force-reinstalls cabal-meta cabal-src
    - cabal-meta install --only-dependencies --enable-tests
script:
    - cabal-meta install --enable-tests

notifications:
    email:
        on_success: never
        on_failure: change